### PR TITLE
Rename&reorder app header items

### PR DESCRIPTION
**Pull request by fayez-nazzal**
This branch is based upon `task-1376`, they share edits within the same file.

- Reordered tabs to "Create flow diagram", "Home"
- Renamed tabs to "Create diagram", "Credits"

### CODE REVIEW

**Comment by fayez-nazzal** [comment]
Screenshot:

image

**Comment by hammady** [comment]
What about that error in the screenshot?

**Comment by fayez-nazzal** [comment]
> What about that error in the screenshot?

I'm running the repo on my local machine, this error was from the start, I think it is because of the empty fields provided

**Comment by hammady** [comment]
Fields are expected to be empty. How did you run it exactly? Did you use the docker container?

**Comment by fayez-nazzal** [comment]
> Fields are expected to be empty. How did you run it exactly? Did you use the docker container?

I followed the following process: 
Install R on my Ubuntu machine => start R session => Install shiny & required dependencies for PRISMA => runApp("PRISMA_flowdiagram")

I didn't use the docker container.

**Comment by fayez-nazzal** [comment]
I guess it is still a dependencies issue. Using the docker container might help, how could I do so?

**Comment by hammady** [comment]
> I guess it is still a dependencies issue. Using the docker container might help, how could I do so?

Just check the README in the target branch.

**Comment by fayez-nazzal** [comment]
@hammady Thank you, Hossam. 

I ran it using the docker container then checked out this PR locally, the screenshot is now updated.

**Review by hammady — APPROVED** [review]

**Pull request merged**
